test: clean up integration test dirs
Otherwise remote git repositories contain commits from older runs,
and tests fail with the following error:

```
! [rejected]        HEAD -> master (fetch first)
error: failed to push some refs to ...
hint: Updates were rejected because the remote contains work that you do
hint: not have locally.
```